# -*- coding: utf-8 -*-
"""career_research_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YbIRwDFuDO9SMtFrs58w_UPZ765cBxR-

# مشروع AI Career Agent
"""

!pip install -q "langchain>=1.4" "langgraph>=1.2.11" "langchain-openai>=1.2" langchain-community langchain-huggingface sentence-transformers pypdf beautifulsoup4 requests

!pip install -q tavily-python

"""## 1. الإعداد"""

import getpass
import operator
import os
import uuid
from typing import Annotated, TypedDict

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from langchain.agents import create_agent
from langchain.agents.middleware import ToolCallLimitMiddleware
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.errors import GraphRecursionError
from langgraph.graph import END, START, StateGraph


def get_secret(name: str) -> str:
    """Colab Secrets first, then environment variables (.env)."""
    value = ''
    try:
        from google.colab import userdata
        value = userdata.get(name) or ''
    except Exception:
        pass
    return value or os.environ.get(name, '')


api_key = get_secret('OPENROUTER_API_KEY') or getpass.getpass('Paste your OPENROUTER_API_KEY: ')
if not api_key:
    raise ValueError('Set OPENROUTER_API_KEY (Colab Secrets, .env, or paste it when asked).')

TAVILY_API_KEY = get_secret('TAVILY_API_KEY')

MODEL_NAME = 'nvidia/nemotron-3.5-lightning:free'
MAX_TOKENS = 4096

llm = ChatOpenAI(
    model=MODEL_NAME,
    base_url='https://openrouter.ai/api/v1',
    api_key=api_key,
    max_tokens=MAX_TOKENS,
    temperature=0.2,
)
print('Model:', MODEL_NAME)
print('Search:', 'Tavily + DuckDuckGo fallback' if TAVILY_API_KEY
      else 'DuckDuckGo only (add TAVILY_API_KEY if you get no results)')

"""## 2. Observability: تتبع كل تشغيل (عدد التوكنز والتكلفة)"""

import asyncio
import functools
import time
import uuid
from contextvars import ContextVar
from dataclasses import dataclass, field
from typing import Any, List, Optional


@dataclass
class Span:
    id: str
    name: str
    start_time: float
    level: int
    type: str = 'span'
    parent: Optional['Span'] = None
    children: List['Span'] = field(default_factory=list)
    end_time: Optional[float] = None
    input: Any = None
    output: Any = None
    metadata: dict = field(default_factory=dict)
    usage: dict = field(default_factory=dict)
    model: Optional[str] = None


_current_span: ContextVar[Optional[Span]] = ContextVar('current_span', default=None)


def print_tree(span: Span):
    duration = (span.end_time - span.start_time) * 1000
    indent = '  ' * span.level
    prefix, suffix = ('=== TRACE: ', ' ===') if span.level == 0 else ('|-- ', '')
    meta_parts = []
    if span.model:
        meta_parts.append(f'model={span.model}')
    if span.usage.get('total_tokens'):
        meta_parts.append(f"tokens={span.usage['total_tokens']}")
    if 'tool_calls' in span.metadata:
        meta_parts.append(f"tool_calls={span.metadata['tool_calls']}")
    if 'cost_usd' in span.metadata:
        meta_parts.append(f"${span.metadata['cost_usd']:.4f}")
    meta_str = f" [{', '.join(meta_parts)}]" if meta_parts else ''
    type_str = f' [{span.type}]' if span.type != 'span' else ''
    print(f'{indent}{prefix}{span.name}{type_str}{suffix} ({duration:.0f}ms){meta_str}')
    for child in span.children:
        print_tree(child)


def _make_span(name, span_type, args, kwargs) -> Span:
    parent = _current_span.get()
    level = parent.level + 1 if parent else 0
    span = Span(id=str(uuid.uuid4())[:8], name=name, type=span_type,
                start_time=time.time(), level=level, parent=parent,
                input={'args': args, 'kwargs': kwargs})
    if parent:
        parent.children.append(span)
    return span


def _finish_span(span: Span):
    span.end_time = time.time()
    if span.level == 0:
        print('\n' + '-' * 60)
        print_tree(span)
        print('-' * 60 + '\n')


def observe(name=None, as_type=None):
    """Record a span around a sync or async function."""
    def decorator(func):
        span_name = name if isinstance(name, str) else func.__name__
        span_type = as_type or 'span'

        if asyncio.iscoroutinefunction(func):
            @functools.wraps(func)
            async def wrapper(*args, **kwargs):
                span = _make_span(span_name, span_type, args, kwargs)
                token = _current_span.set(span)
                try:
                    result = await func(*args, **kwargs)
                    if span.output is None:
                        span.output = result
                    return result
                except Exception as e:
                    span.output = f'Error: {e}'
                    raise
                finally:
                    _current_span.reset(token)
                    _finish_span(span)
        else:
            @functools.wraps(func)
            def wrapper(*args, **kwargs):
                span = _make_span(span_name, span_type, args, kwargs)
                token = _current_span.set(span)
                try:
                    result = func(*args, **kwargs)
                    if span.output is None:
                        span.output = result
                    return result
                except Exception as e:
                    span.output = f'Error: {e}'
                    raise
                finally:
                    _current_span.reset(token)
                    _finish_span(span)
        return wrapper

    if callable(name):
        func, name = name, None
        return decorator(func)
    return decorator


class LangfuseContext:
    """Attach usage/model/cost data to the span currently being recorded."""
    def update_current_observation(self, **kwargs):
        span = _current_span.get()
        if not span:
            return
        if isinstance(kwargs.get('usage'), dict):
            span.usage.update(kwargs['usage'])
        if 'model' in kwargs:
            span.model = kwargs['model']
        if isinstance(kwargs.get('metadata'), dict):
            span.metadata.update(kwargs['metadata'])


langfuse_context = LangfuseContext()

"""## 3. LoopDetector: يكشف تكرار الوكيل لنفسه"""

@dataclass
class LoopDetectionResult:
    is_looping: bool
    strategy: str  # 'exact', 'fuzzy', 'stagnation', or 'none'
    message: str
    confidence: float


class LoopDetector:
    """Detects loops using exact match, fuzzy match, and output stagnation."""

    def __init__(self, exact_threshold: int = 2, fuzzy_threshold: float = 0.85,
                 stagnation_window: int = 3):
        self.exact_threshold = exact_threshold
        self.fuzzy_threshold = fuzzy_threshold
        self.stagnation_window = stagnation_window
        self.tool_history: list[tuple[str, str]] = []
        self.output_history: list[str] = []

    def _jaccard_similarity(self, s1: str, s2: str) -> float:
        t1, t2 = set(s1.lower().split()), set(s2.lower().split())
        if not t1 and not t2:
            return 1.0
        if not t1 or not t2:
            return 0.0
        return len(t1 & t2) / len(t1 | t2)

    def check_tool_call(self, tool_name: str, tool_input: str) -> LoopDetectionResult:
        current = (tool_name, tool_input.strip())
        exact_count = sum(1 for n, i in self.tool_history if (n, i.strip()) == current)
        if exact_count >= self.exact_threshold:
            self.tool_history.append(current)
            return LoopDetectionResult(
                True, 'exact',
                f"Exact loop: '{tool_name}' called {exact_count + 1} times with identical arguments.",
                1.0)
        recent = self.tool_history[-5:]
        fuzzy = sum(1 for n, i in recent
                    if n == tool_name and self._jaccard_similarity(tool_input, i) >= self.fuzzy_threshold)
        if fuzzy >= self.exact_threshold:
            self.tool_history.append(current)
            return LoopDetectionResult(
                True, 'fuzzy',
                f"Fuzzy loop: '{tool_name}' called {fuzzy + 1} times with very similar arguments.",
                0.85)
        self.tool_history.append(current)
        return LoopDetectionResult(False, 'none', '', 0.0)

    def check_output_stagnation(self, output: str) -> LoopDetectionResult:
        self.output_history.append(output)
        if len(self.output_history) < self.stagnation_window:
            return LoopDetectionResult(False, 'none', '', 0.0)
        recent = self.output_history[-self.stagnation_window:]
        sims = [self._jaccard_similarity(recent[i], recent[j])
                for i in range(len(recent)) for j in range(i + 1, len(recent))]
        avg = sum(sims) / len(sims) if sims else 0.0
        if avg >= self.fuzzy_threshold:
            return LoopDetectionResult(
                True, 'stagnation',
                f'Last {self.stagnation_window} outputs are {avg:.0%} similar: no progress.',
                avg)
        return LoopDetectionResult(False, 'none', '', 0.0)

    def reset(self):
        self.tool_history.clear()
        self.output_history.clear()


# Shared detectors used by the tools and the pipeline below.
tool_detector = LoopDetector(exact_threshold=2, fuzzy_threshold=0.9)  # repeated tool calls
research_detector = LoopDetector(stagnation_window=2)                 # repeated research output
loop_alerts: list[str] = []


def _loop_guard(tool_name: str, tool_input: str):
    """Runs BEFORE a web tool executes. If the agent is repeating itself, the tool is
    skipped and the agent is told to change approach."""
    check = tool_detector.check_tool_call(tool_name, tool_input)
    if check.is_looping:
        loop_alerts.append(f'[{tool_name}] {check.message}')
        print(f'[LoopDetector] {check.message}')
        return (f'LOOP_DETECTED: {check.message} Use a clearly different query, '
                f'or finish with the information you already have.')
    return None

"""## 4. أدوات البحث على الإنترنت"""

import ipaddress
import logging
import socket
from urllib.parse import parse_qs, urlparse

import requests
from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)
HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
BAD_PREFIXES = ('SEARCH_UNAVAILABLE', 'LOOP_DETECTED', 'No results', 'Search failed', 'Error')


def validate_url(url: str) -> bool:
    """Block non-http(s) schemes and private/loopback addresses (SSRF protection)."""
    try:
        parsed = urlparse(url)
        if parsed.scheme not in ('http', 'https') or not parsed.hostname:
            return False
        for info in socket.getaddrinfo(parsed.hostname, None):
            ip = ipaddress.ip_address(info[4][0])
            if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved or ip.is_multicast:
                return False
        return True
    except Exception:
        return False


def _clean_ddg_link(href: str) -> str:
    if href.startswith('//'):
        href = 'https:' + href
    parsed = urlparse(href)
    if 'duckduckgo.com' in (parsed.netloc or '') and parsed.path.startswith('/l/'):
        target = parse_qs(parsed.query).get('uddg')
        if target:
            return target[0]
    return href


def _search_tavily(query: str, max_results: int):
    from tavily import TavilyClient
    resp = TavilyClient(api_key=TAVILY_API_KEY).search(query, max_results=max_results)
    return [(r.get('title', ''), r.get('url', ''), (r.get('content') or '')[:300])
            for r in resp.get('results', [])]


def _search_ddg(query: str, max_results: int):
    response = requests.post('https://html.duckduckgo.com/html/', data={'q': query},
                             headers=HEADERS, timeout=15)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, 'html.parser')
    hits = []
    for result in soup.find_all('div', class_='result', limit=max_results * 2):
        title_tag = result.find('a', class_='result__a')
        if not title_tag:
            continue
        snippet_tag = result.find('a', class_='result__snippet')
        hits.append((title_tag.get_text(strip=True),
                     _clean_ddg_link(title_tag.get('href', '')),
                     snippet_tag.get_text(strip=True) if snippet_tag else ''))
    return hits


def _format_hits(hits) -> str:
    return '\n\n'.join(f'{i}. {t}\n   Link: {u}\n   Snippet: {s}' for i, (t, u, s) in enumerate(hits, 1))


@tool('search_web')
def search_web(query: str, max_results: int = 5) -> str:
    """Search the web for a query. Returns a list of results with title, link and snippet."""
    blocked = _loop_guard('search_web', query)
    if blocked:
        return blocked
    providers = ([('Tavily', _search_tavily)] if TAVILY_API_KEY else []) + [('DuckDuckGo', _search_ddg)]
    problems = []
    for name, search in providers:
        try:
            hits = [h for h in search(query, max_results) if validate_url(h[1])][:max_results]
            if hits:
                return _format_hits(hits)
            problems.append(f'{name}: no results')
        except Exception as e:
            logger.error(f'{name} search failed: {e}')
            problems.append(f'{name}: {e}')
    return ('SEARCH_UNAVAILABLE: ' + '; '.join(problems) +
            '. Do not invent sources; mark anything you add as general knowledge.')
@tool('read_webpage')
def read_webpage(url: str) -> str:
    """Read the content of a webpage. Returns the text content."""
    blocked = _loop_guard('read_webpage', url)
    if blocked:
        return blocked
    if not validate_url(url):
        return 'Error: Invalid or restricted URL.'
    try:
        response = requests.get(url, headers=HEADERS, timeout=15)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        for el in soup(['script', 'style']):
            el.decompose()
        lines = (line.strip() for line in soup.get_text(separator='\n').splitlines())
        return '\n'.join(line for line in lines if line)[:8000]
    except Exception as e:
        return f'Error reading {url}: {e}'


RESEARCH_TOOLS = [search_web, read_webpage]

# Smoke test (needs internet)
_test = search_web.invoke({'query': 'AI engineer entry level jobs Saudi Arabia'})
print(_test[:500])
if _test.startswith(BAD_PREFIXES):
    print('\n>>> Web search is NOT working. Add TAVILY_API_KEY to Colab Secrets and re-run from the setup cell.')

"""## 5. الـ Runner المشترك: ينفذ الوكيل ويحسب التوكنز والتكلفة وأدوات الاستخدام الفعلية"""

@observe(name='agent_run', as_type='agent')
async def run_agent(agent, query: str, max_steps: int = 10, thread_id: str | None = None) -> dict:
    config = {'recursion_limit': 2 * max_steps + 1}
    if thread_id:
        config['configurable'] = {'thread_id': thread_id}
    try:
        result = await agent.ainvoke({'messages': [('user', query)]}, config=config)
        all_messages = result['messages']
        answer = all_messages[-1].content
        start = max((i for i, m in enumerate(all_messages) if getattr(m, 'type', '') == 'human'), default=0)
        messages = all_messages[start:]
    except GraphRecursionError:
        messages, answer = [], 'Agent stopped: step limit reached.'

    if isinstance(answer, list):
        answer = ''.join(b.get('text', '') if isinstance(b, dict) else str(b) for b in answer)
    if not str(answer).strip():
        answer = '(empty answer)'

    total_tokens = sum((getattr(m, 'usage_metadata', None) or {}).get('total_tokens', 0) for m in messages)
    total_cost = sum(
        float(((getattr(m, 'response_metadata', None) or {}).get('token_usage') or {}).get('cost') or 0)
        for m in messages)
    tool_calls = [(tc['name'], str(tc['args']))
                  for m in messages for tc in (getattr(m, 'tool_calls', None) or [])]
    tool_results = [(getattr(m, 'name', None) or '', not str(getattr(m, 'content', '')).startswith(BAD_PREFIXES))
                    for m in messages if getattr(m, 'type', '') == 'tool']
    last_meta = (getattr(messages[-1], 'response_metadata', None) or {}) if messages else {}
    truncated = last_meta.get('finish_reason') in ('length', 'MAX_TOKENS')

    langfuse_context.update_current_observation(
        usage={'total_tokens': total_tokens}, model=MODEL_NAME,
        metadata={'cost_usd': round(total_cost, 6), 'tool_calls': len(tool_calls)})

    return {'answer': answer, 'tool_calls': tool_calls, 'tool_results': tool_results,
            'truncated': truncated, 'failed': False,
            'metadata': {'total_messages': len(messages), 'total_tokens': total_tokens,
                         'cost_usd': total_cost}}


async def safe_run(stage: str, agent, prompt: str, thread_id: str | None = None) -> dict:
    """A failing agent must not crash the whole pipeline."""
    try:
        return await run_agent(agent, prompt, 10, thread_id)
    except Exception as e:
        print(f'[{stage}] FAILED: {e}')
        return {'answer': f'[{stage} failed: {e}]', 'tool_calls': [], 'tool_results': [],
                'truncated': False, 'failed': True,
                'metadata': {'total_messages': 0, 'total_tokens': 0, 'cost_usd': 0.0}}

"""## 6. (RAG)

"""

from langchain_community.document_loaders import PyPDFLoader
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

CV_PATH = 'my_cv.pdf'
if not os.path.exists(CV_PATH):
    try:
        from google.colab import files
        print('Please upload your CV as a PDF.')
        uploaded = files.upload()
        os.rename(next(iter(uploaded)), CV_PATH)
    except ImportError:
        raise FileNotFoundError(f'Put your CV next to this notebook as {CV_PATH}')

docs = PyPDFLoader(CV_PATH).load()
assert sum(len(d.page_content.strip()) for d in docs) > 50, \
    'No text found in the CV (it may be a scanned image). Upload a text-based PDF.'

splits = RecursiveCharacterTextSplitter(
    chunk_size=1000, chunk_overlap=200, add_start_index=True).split_documents(docs)
embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
vector_store = InMemoryVectorStore(embeddings)
vector_store.add_documents(documents=splits)
retriever = vector_store.as_retriever(search_kwargs={'k': 3})


@tool('search_my_cv')
def search_my_cv(query: str) -> str:
    """Retrieve information from the user's CV (skills, projects, education, experience)."""
    return '\n\n'.join(d.page_content for d in retriever.invoke(query))


print(f'CV indexed: {len(docs)} page(s), {len(splits)} chunk(s).')

"""## 7.  البرومبتات"""

RESEARCHER_PROMPT = """
You are a Tech Career Scout specializing in the Saudi Arabian technology job market.
Your task is to research CURRENT job-market requirements for the roles in the user's request.

You will usually receive web search results that were already collected for you. You MUST:
1. Base your report on those results and on anything you find with search_web / read_webpage.
   Use search_web again (with DIFFERENT queries) or read_webpage when the results are thin.
2. Report only what the sources support: specific skills, programming languages, tools, frameworks,
   cloud platforms and certifications.
3. End with a "Sources" section listing the links you used.

If no search results are provided and the tools return SEARCH_UNAVAILABLE or LOOP_DETECTED, say clearly
that web search was unavailable and mark everything you add as "general knowledge".
Never invent job postings or links. Keep the report under 400 words.
"""

ANALYST_PROMPT = """
You are a Career Skill Gap Analyst.
You receive research about the Saudi technology job market.

You MUST:
1. Call search_my_cv several times with DIFFERENT queries (skills, projects, education, work experience,
   certifications) to retrieve the user's real background. Never guess what is in the CV.
   (If you already retrieved the CV earlier in this conversation you may reuse it.)
2. Compare the CV against the researched market requirements.
3. Output exactly these sections:
   ## Skills you already have (with evidence from the CV)
   ## Missing skills (ordered by priority, naming SPECIFIC tools and technologies)
   ## Notes
Keep it under 400 words.
"""

WRITER_PROMPT = """
You are a Career Coach.
Use the market research and the skill-gap analysis to create a personalized 3-Month Action Plan.

The plan MUST:
1. Be based only on the information provided by the previous agents.
2. Mention SPECIFIC technologies and tools.
3. Be divided into Month 1, Month 2 and Month 3, each with weekly goals and one concrete deliverable
   (a portfolio project, a certification, or an application milestone).
4. Build on the user's existing skills.
5. Be complete: always finish Month 3. Keep it under 600 words.

If the analysis does not contain enough specific technical tools or lacks evidence from the CV,
output ONLY the single word:
NEEDS_SPECIFIC_TOOLS
"""

"""## 8. بناء الوكلاء الثلاثة"""

RESEARCH_TOOL_LIMIT = 10
ANALYST_TOOL_LIMIT = 10

researcher = create_agent(
    model=llm,
    tools=RESEARCH_TOOLS,
    system_prompt=RESEARCHER_PROMPT,
    middleware=[ToolCallLimitMiddleware(thread_limit=RESEARCH_TOOL_LIMIT, exit_behavior='end')],
)
analyst = create_agent(
    model=llm,
    tools=[search_my_cv],
    system_prompt=ANALYST_PROMPT,
    middleware=[ToolCallLimitMiddleware(thread_limit=ANALYST_TOOL_LIMIT, exit_behavior='end')],
    checkpointer=InMemorySaver(),
)
writer = create_agent(model=llm, tools=[], system_prompt=WRITER_PROMPT)
print('Agents ready.')

"""## 9. Pipeline (Graph)مع حلقة"""

MAX_RETRIES = 1


class PipelineState(TypedDict):
    query: str
    thread_id: str
    research: str
    analysis: str
    report: str
    attempts: int
    stalled: bool
    runs: Annotated[list, operator.add]


def _record(stage: str, result: dict) -> dict:
    return {'stage': stage,
            'tokens': result['metadata']['total_tokens'],
            'cost_usd': result['metadata']['cost_usd'],
            'tools': [name for name, _ in result['tool_calls']],
            'search_ok': sum(1 for n, ok in result['tool_results'] if n == 'search_web' and ok),
            'truncated': result['truncated'],
            'failed': result['failed']}


def _seed_search(query: str, attempt: int):
    """Run the web searches ourselves, so the research is grounded even when the model skips tools."""
    if attempt == 0:
        queries = [f'{query} job requirements skills', f'{query} job postings Riyadh Jeddah']
    else:
        queries = [f'{query} required tools frameworks cloud certifications',
                   f'{query} Saudi job description tech stack']
    blocks, ok = [], 0
    for q in queries:
        result = search_web.invoke({'query': q})
        if not result.startswith(BAD_PREFIXES):
            ok += 1
            blocks.append(f'### Search: {q}\n{result}')
    return '\n\n'.join(blocks), ok, len(queries)


async def researcher_node(state: PipelineState) -> dict:
    query = state['query']
    if state['attempts'] > 0:
        query = (
            f"Original request: {state['query']}\n\n"
            'A previous attempt did not produce enough SPECIFIC technical tools. Focus ONLY on finding '
            'concrete, named tools, frameworks, cloud platforms and certifications that appear in real '
            'Saudi job postings. Use different search queries than before.'
        )
    seed_text, seed_ok, seed_total = await asyncio.to_thread(_seed_search, state['query'], state['attempts'])
    if seed_text:
        query += f'\n\nSearch results already collected for you:\n{seed_text}'
    else:
        print('[Search] the pre-search returned nothing; the agent will try the tools itself.')

    result = await safe_run('researcher', researcher, query)
    record = _record('researcher', result)
    record['search_ok'] += seed_ok
    record['tools'] = ['search_web(pre-search)'] * seed_total + record['tools']

    check = research_detector.check_output_stagnation(result['answer'])
    if check.is_looping:
        loop_alerts.append(f'[researcher] {check.message}')
        print(f'[LoopDetector] [researcher] {check.message}')
    return {'research': result['answer'], 'stalled': check.is_looping, 'runs': [record]}


def route_after_researcher(state: PipelineState) -> str:
    if state['stalled']:
        print('[Router]: research did not change, skipping re-analysis and going straight to the writer.')
        return 'writer'
    return 'analyst'


async def analyst_node(state: PipelineState) -> dict:
    prompt = (
        f"Market research:\n{state['research']}\n\n"
        'Task: use search_my_cv to read my real CV, then compare it with this research.'
    )
    result = await safe_run('analyst', analyst, prompt, thread_id=state['thread_id'])
    return {'analysis': result['answer'], 'runs': [_record('analyst', result)]}


async def writer_node(state: PipelineState) -> dict:
    prompt = (
        f"Market research:\n{state['research']}\n\n"
        f"Skill-gap analysis:\n{state['analysis']}"
    )
    if state['attempts'] >= 1:
        prompt += (
            '\n\nThis is a retry after a quality check. Write the plan now using the most specific tools '
            'available above and clearly flag any assumption. Do NOT output NEEDS_SPECIFIC_TOOLS.'
        )
    result = await safe_run('writer', writer, prompt)
    return {'report': result['answer'],
            'attempts': state['attempts'] + 1,
            'runs': [_record('writer', result)]}


def review_condition(state: PipelineState) -> str:
    if state['report'].startswith('[writer failed'):
        return END
    if 'NEEDS_SPECIFIC_TOOLS' in state['report'] and state['attempts'] <= MAX_RETRIES:
        print('\n[Quality Check]: plan is not specific enough.')
        print('[Router]: sending the task back to the researcher...\n')
        return 'researcher'
    return END


graph = StateGraph(PipelineState)
graph.add_node('researcher', researcher_node)
graph.add_node('analyst', analyst_node)
graph.add_node('writer', writer_node)
graph.add_edge(START, 'researcher')
graph.add_conditional_edges('researcher', route_after_researcher,
                            {'analyst': 'analyst', 'writer': 'writer'})
graph.add_edge('analyst', 'writer')
graph.add_conditional_edges('writer', review_condition, {'researcher': 'researcher', END: END})
pipeline = graph.compile()


@observe(name='career_pipeline', as_type='chain')
async def run_pipeline(query: str) -> dict:
    research_detector.reset()
    tool_detector.reset()
    loop_alerts.clear()

    final = await pipeline.ainvoke(
        {'query': query, 'thread_id': f'run-{uuid.uuid4().hex[:8]}', 'research': '', 'analysis': '',
         'report': '', 'attempts': 0, 'stalled': False, 'runs': []},
        config={'recursion_limit': 25},
    )

    runs = final['runs']
    researcher_runs = [r for r in runs if r['stage'] == 'researcher']
    writer_runs = [r for r in runs if r['stage'] == 'writer']
    grounded = any(r['search_ok'] > 0 for r in researcher_runs)
    truncated = bool(writer_runs and writer_runs[-1]['truncated'])
    unresolved = 'NEEDS_SPECIFIC_TOOLS' in final['report']

    plan = final['report'].replace('NEEDS_SPECIFIC_TOOLS', '').strip()
    if not plan:
        plan = 'The agents could not produce a specific plan. Try a more detailed query or CV.'

    notes = []
    if not grounded:
        notes.append('Web search was unavailable or returned nothing: the market requirements below come '
                     'from the model general knowledge, not from verified job postings.')
    if final['stalled']:
        notes.append('The retry research repeated the first one, so the plan is based on limited evidence.')
    if any(r['failed'] for r in runs):
        notes.append('One or more agents failed (for example a rate limit or credit error). '
                     'See the log above, fix it and run again.')
    if truncated:
        notes.append('The plan was cut off by the token limit. Raise MAX_TOKENS and run again.')
    if notes:
        plan = '\n'.join(f'> **Warning:** {n}' for n in notes) + '\n\n' + plan

    tool_names = [t for r in runs for t in r['tools']]
    analyst_calls = [len(r['tools']) for r in runs if r['stage'] == 'analyst']
    researcher_calls = [len(r['tools']) for r in researcher_runs]

    return {
        'answer': plan,
        'metadata': {
            'agent_runs': len(runs),
            'retries_used': final['attempts'] - 1,
            'grounded': grounded,
            'stalled': final['stalled'],
            'truncated': truncated,
            'unresolved': unresolved,
            'search_ok': sum(r['search_ok'] for r in runs),
            'tool_counts': {n: tool_names.count(n) for n in sorted(set(tool_names))},
            'researcher_calls': researcher_calls,
            'analyst_calls': analyst_calls,
            'total_tokens': sum(r['tokens'] for r in runs),
            'total_cost_usd': sum(r['cost_usd'] for r in runs),
            'loop_alerts': list(loop_alerts),
            'within_budget': (all(c <= RESEARCH_TOOL_LIMIT for c in researcher_calls)
                              and sum(analyst_calls) <= ANALYST_TOOL_LIMIT),
        },
    }

"""## 10. التشغيل"""

QUERY = 'AI Engineer and Data Analyst entry-level jobs in Saudi Arabia'

pipeline_result = await run_pipeline(QUERY)
m = pipeline_result['metadata']

print('=' * 60)
print('RUN SUMMARY (computed from this run)')
print('=' * 60)
print(f"Agent runs         : {m['agent_runs']}  (retries used: {m['retries_used']})")
print(f"Tokens / cost      : {m['total_tokens']} / ${m['total_cost_usd']:.4f}")
print(f"Tool calls         : {m['tool_counts'] or 'none'}")
print(f"Web evidence       : {m['search_ok']} successful search(es) -> "
      f"{'grounded in sources' if m['grounded'] else 'NOT grounded (general knowledge)'}")
print(f"CV retrieval used  : {'yes' if m['tool_counts'].get('search_my_cv') else 'NO'}")
print(f"Step budget        : researcher {m['researcher_calls']} / {RESEARCH_TOOL_LIMIT} per run, "
      f"analyst {sum(m['analyst_calls'])} / {ANALYST_TOOL_LIMIT} -> {'kept' if m['within_budget'] else 'EXCEEDED'}")
print(f"Loop alerts        : {len(m['loop_alerts'])} {m['loop_alerts']}")
print(f"Research stalled   : {'yes' if m['stalled'] else 'no'}")
print(f"Output truncated   : {'YES, raise MAX_TOKENS' if m['truncated'] else 'no'}")
if m['unresolved']:
    print('WARNING: the plan was still not specific after the retry.')

from IPython.display import Markdown, display
display(Markdown(pipeline_result['answer']))

from google.colab import files

with open('action_plan.md', 'w', encoding='utf-8') as f:
    f.write(pipeline_result['answer'])
files.download('action_plan.md')